### PR TITLE
fix: Split version number from pin

### LINKED ISSUE #8: downgradable_packages() is sometimes not selecting the latest available version
While testing https://github.com/pop-os/upgrade/pull/341, I discovered that in the following scenario:

- `ansible-core` installed from its PPA as version `2.17.6-1ppa~jammy`
- Available from Ubuntu's `jammy/universe` as version `2.12.0-1` and from Ubuntu's `jammy-updates/universe` as version `2.12.0-1ubuntu0.1`

When pop-upgrade calls `downgradable_packages()`, it then attempts to install version `2.12.0-1`, which has a [packaging issue](https://bugs.launchpad.net/ubuntu/+source/ansible-core/+bug/1969917) that prevents installation when the main `ansible` package isn't present. `apt policy` recognizes that `2.12.0-1ubuntu0.1` is the correct candidate version (and that version has the packaging issue fixed).

**Expected behavior:**

`downgradable_packages()` should return `2.12.0-1ubuntu0.1` as the version in this case, since that is the correct candidate version once the PPA's been removed and the installed version is orphaned.

### PR DESCRIPTION
**Pull request by jacobgkau**
Confirmed this fixes https://github.com/pop-os/apt-cmd/issues/8.

### CODE REVIEW

File: src/apt_cache.rs [hunk 1]
```diff
@@ -68,9 +68,13 @@ pub fn policies(lines: impl Stream<Item = io::Result<String>>) -> impl Stream<It
...
                             .push(source.trim().to_owned());
                     } else if let Some(version) = line.strip_prefix(" *** ") {
-                        current_version = version.trim().to_owned();
+                        let mut current_version_and_pin = version.trim().split_whitespace();
+                        current_version = current_version_and_pin.next().unwrap().to_owned();
+                        // TODO: Store & use pin.
                     } else if let Some(version) = line.strip_prefix("   ") {
-                        current_version = version.trim().to_owned();
+                        let mut current_version_and_pin = version.trim().split_whitespace();
+                        current_version = current_version_and_pin.next().unwrap().to_owned();
```
Comment (mmstick) [inline src/apt_cache.rs]: Since unwrapping creates a panic on `None`, it may be better to ignore lines that for some reason have no version.

```rs
if let Some(version) =  current_version_and_pin.next() {
    current_version = version.to_owned();
}
```

Comment (jacobgkau) [reply src/apt_cache.rs]: Seems more important for the second invocation of `.next()` since getting into the `if let Some(version) = line.strip_prefix("   ")` block means there's at least one string we're working with, but I guess this would guard against if a line was _just_ the prefix we're stripping/other whitespace?

Comment (mmstick) [reply src/apt_cache.rs]: Yes, this would guard against the line having a prefix but nothing after. Alternatively, we could set an `.expect("")` here to explain why the unwrap should never fail.

**Review by mmstick — APPROVED** [review]
